name: exposys_virtual_internship_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get:



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  basic_utils: ^5.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/software.png"
  min_sdk_android: 21
  remove_aplha_icons: true





  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - images/
    - images/





