// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWwWCPHP4w6D0uevND47Mn-NY48-aD2zY',
    appId: '1:435902048512:android:38afc43716bc6c6ee06be5',
    messagingSenderId: '435902048512',
    projectId: 'exposys-virtual-internsh-6d733',
    storageBucket: 'exposys-virtual-internsh-6d733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb17NBVBo8gT_xVPB8Wm42wYnkxEPw-Zk',
    appId: '1:435902048512:ios:eefbfd0bf52c6445e06be5',
    messagingSenderId: '435902048512',
    projectId: 'exposys-virtual-internsh-6d733',
    storageBucket: 'exposys-virtual-internsh-6d733.appspot.com',
    iosClientId: '435902048512-gnvgri5pvgdicv477avk9hufc1vssech.apps.googleusercontent.com',
    iosBundleId: 'com.example.exposysVirtualInternshipApp',
  );
}
